import { EngineInstance, FaultEvent, Mission, MroTask } from '../types';

export const INITIAL_MISSION: Mission = {
  id: 'MSN-2026-ISR-088',
  assetId: 'UAV-01',
  missionName: 'HIGH ALTITUDE ISR',
  missionType: 'Autonomous Strategic Reconnaissance',
  phase: 'LOITER // AUTONOMOUS',
  altitudeFt: 18000,
  airspeedKt: 198,
  fuelRemainingPct: 64,
  remainingTime: '04h 32m',
  missionProgressPct: 68,
  linkStatus: 'SATCOM // ENCRYPTED 256-BIT',
  cameraStatus: 'FLIR INFRARED ACTIVE',
  fovDegrees: 84,
  stabilization: '3-AXIS LOCK',
  targetLock: 'DISENGAGED // RECON MATRIX',
  latLong: "S 34°52', W 70°15'",
  callsign: 'CDR. V. SHASTRI',
  rank: 'LEVEL 2 // FLIGHT CONTROLLER',
};

export const INITIAL_ENGINES: EngineInstance[] = [
  {
    id: 'ENG 01',
    index: 0,
    name: 'Lycoming O-320 (Port Inboard)',
    model: 'Lycoming O-320 Propulsion System',
    position: 'Port Inboard',
    health: 92,
    status: 'HEALTHY // OPTIMAL',
    statusColor: '#10b981',
    rul: 184,
    telemetry: {
      rpm: 2447,
      cht: 178,
      egt: 690,
      oilPressure: 82,
      oilTemperature: 85,
      fuelFlow: 32.5,
      vibration: 2.1,
      batteryVoltage: 28.2,
      alternatorCurrent: 44.5,
      manifoldPressure: 24.8,
      cylinderTemps: [178, 174, 180, 176],
      harmonicFreq: 124.8,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 99.4,
      syncStatus: 'SYNCHRONIZED',
      syntheticTwinId: 'SYNTHETIC TWIN D-04',
      azimuth: 114,
      elevation: -12.4,
      frameRefreshHz: 60,
      latencyMs: 12,
      subsystems: {
        fuelDelivery: 95,
        coolingAirflow: 84,
        lubricationSump: 90,
        dualMagnetosSpark: 98,
      },
    },
  },
  {
    id: 'ENG 02',
    index: 1,
    name: 'Lycoming O-320 (Port Outboard)',
    model: 'Lycoming O-320 Propulsion System',
    position: 'Port Outboard',
    health: 74,
    status: 'WARNING // THERMAL DRIFT',
    statusColor: '#f59e0b',
    rul: 82,
    telemetry: {
      rpm: 2490,
      cht: 216,
      egt: 742,
      oilPressure: 72,
      oilTemperature: 98,
      fuelFlow: 36.2,
      vibration: 3.4,
      batteryVoltage: 27.9,
      alternatorCurrent: 42.1,
      manifoldPressure: 25.1,
      cylinderTemps: [204, 218, 216, 212],
      harmonicFreq: 128.2,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 96.8,
      syncStatus: 'DRIFT_DETECTED',
      syntheticTwinId: 'SYNTHETIC TWIN D-04',
      azimuth: 114,
      elevation: -12.4,
      frameRefreshHz: 60,
      latencyMs: 15,
      subsystems: {
        fuelDelivery: 88,
        coolingAirflow: 61,
        lubricationSump: 79,
        dualMagnetosSpark: 96,
      },
    },
  },
  {
    id: 'ENG 03',
    index: 2,
    name: 'Lycoming O-320 (Starboard Inboard)',
    model: 'Lycoming O-320 Propulsion System',
    position: 'Starboard Inboard',
    health: 41,
    status: 'CRITICAL // BEARING WEAR',
    statusColor: '#ef4444',
    rul: 18,
    telemetry: {
      rpm: 2310,
      cht: 194,
      egt: 705,
      oilPressure: 54,
      oilTemperature: 104,
      fuelFlow: 34.0,
      vibration: 4.8,
      batteryVoltage: 27.6,
      alternatorCurrent: 39.8,
      manifoldPressure: 23.9,
      cylinderTemps: [194, 190, 196, 192],
      harmonicFreq: 119.5,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 94.2,
      syncStatus: 'DRIFT_DETECTED',
      syntheticTwinId: 'SYNTHETIC TWIN D-04',
      azimuth: 114,
      elevation: -12.4,
      frameRefreshHz: 60,
      latencyMs: 18,
      subsystems: {
        fuelDelivery: 82,
        coolingAirflow: 75,
        lubricationSump: 42,
        dualMagnetosSpark: 91,
      },
    },
  },
  {
    id: 'ENG 04',
    index: 3,
    name: 'Lycoming O-320 (Starboard Outboard)',
    model: 'Lycoming O-320 Propulsion System',
    position: 'Starboard Outboard',
    health: 96,
    status: 'HEALTHY // OPTIMAL',
    statusColor: '#10b981',
    rul: 220,
    telemetry: {
      rpm: 2455,
      cht: 172,
      egt: 685,
      oilPressure: 84,
      oilTemperature: 83,
      fuelFlow: 31.8,
      vibration: 1.8,
      batteryVoltage: 28.4,
      alternatorCurrent: 45.0,
      manifoldPressure: 24.9,
      cylinderTemps: [172, 170, 174, 171],
      harmonicFreq: 125.1,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 99.7,
      syncStatus: 'SYNCHRONIZED',
      syntheticTwinId: 'SYNTHETIC TWIN D-04',
      azimuth: 114,
      elevation: -12.4,
      frameRefreshHz: 60,
      latencyMs: 11,
      subsystems: {
        fuelDelivery: 97,
        coolingAirflow: 93,
        lubricationSump: 95,
        dualMagnetosSpark: 99,
      },
    },
  },
];

export const INITIAL_ALERTS: FaultEvent[] = [
  {
    id: 'ALT-1092',
    engineId: 'ENG 03',
    engineIndex: 2,
    severity: 'CRITICAL',
    title: 'CRITICAL: RUL EXPIRATION RISK',
    component: 'Crank Journal Bearing Hub',
    description: 'Engine 03 // 18 hrs remaining before bearing threshold',
    timestamp: '19:46:12Z',
    actionLabel: 'INSPECT',
  },
  {
    id: 'ALT-1088',
    engineId: 'ENG 02',
    engineIndex: 1,
    severity: 'WARNING',
    title: 'WARNING: COOLING THERMAL DRIFT',
    component: 'Baffle Airflow / Cyl #3 Head',
    description: 'Engine 02 // Cyl Head Temp rising +1.8°C/min',
    timestamp: '19:42:05Z',
    actionLabel: 'DIAGNOSE',
  },
  {
    id: 'ALT-1075',
    engineId: 'ENG 01',
    engineIndex: 0,
    severity: 'NORMAL',
    title: 'ADVISORY: FLIGHT ENVELOPE OPTIMAL',
    component: 'FADEC Cruise Governor',
    description: 'Cruise fuel burn matched to high-altitude loiter path',
    timestamp: '19:35:40Z',
    actionLabel: 'NOMINAL',
  },
];

export const INITIAL_MRO_TASKS: MroTask[] = [
  {
    id: 'MRO-801',
    engineId: 'ENG 03',
    engineIndex: 2,
    title: 'ENG 03 CRANK BEARING',
    component: 'Crank Bearing Assembly',
    severity: 'CRITICAL',
    hoursRemaining: 18,
    description: 'Stage 2 Acoustic degradation. Ground replacement needed.',
    statusText: '18 HRS LEFT',
  },
  {
    id: 'MRO-802',
    engineId: 'ENG 02',
    engineIndex: 1,
    title: 'ENG 02 INJECTOR NOZZLE',
    component: 'Fuel Injector Nozzle Matrix',
    severity: 'WARNING',
    hoursRemaining: 46,
    description: 'Ultrasonic flush & calibration scheduled.',
    statusText: '46 HRS LEFT',
  },
  {
    id: 'MRO-803',
    engineId: 'ENG 01',
    engineIndex: 0,
    title: 'ENG 01 OIL & FILTER CYCLE',
    component: 'Full-Flow Spin-On Filter & Sump',
    severity: 'NORMAL',
    hoursRemaining: 184,
    description: 'Spectrometric oil analysis nominal.',
    statusText: '184 HRS LEFT',
  },
];
