import {
  CandidateConfig,
  EngineInstance,
  FaultEvent,
  MaintenanceRecord,
  Mission,
  TelemetryHistoryPoint,
  TuningParameters,
} from '../types';

export const INITIAL_MISSION: Mission = {
  id: 'MSN-774-ALPHA',
  assetId: 'UAV-01 (MALE CLASS)',
  missionName: 'STRATEGIC BORDER RECONNAISSANCE',
  missionType: 'High-Altitude ISR Long-Loiter',
  phase: 'LOITER // AUTONOMOUS',
  altitudeFt: 18450,
  airspeedKt: 204,
  fuelRemainingPct: 62,
  remainingTime: '05h 18m',
  missionProgressPct: 68,
  linkStatus: 'SATCOM ENCRYPTED 256-BIT // MIL-STD-810G',
  cameraStatus: 'FLIR INFRARED ACTIVE',
  fovDegrees: 84,
  stabilization: '3-AXIS GYRO LOCK',
  targetLock: 'DISENGAGED // RECON MATRIX',
  latLong: "28°36'48\"N 77°12'04\"E",
  callsign: 'DHRUVA-LEAD [CDR. V. SHASTRI]',
  rank: 'CHIEF FLIGHT CONTROLLER (LEVEL 2)',
  targetAltitudeFt: 22000,
  ambientTempC: -22,
  baroInHg: 15.2,
  burnRateLh: 31.4,
  uavCallsign: 'DHRUVA-01',
};

export const INITIAL_ENGINES: EngineInstance[] = [
  {
    id: 'eng-01',
    index: 0,
    name: 'Lycoming O-320 (Port Inboard)',
    model: 'Lycoming O-320 Aero Piston',
    position: 'Port Inboard',
    health: 96,
    status: 'HEALTHY // OPTIMAL',
    statusColor: '#10b981',
    rul: 248,
    callsign: 'PORT INBOARD // MOD-01',
    engineNumber: 'ENG-01-PI',
    serialNumber: 'SN-LYC-90142',
    totalFlightHours: 382.4,
    uavId: 'UAV-DHRUVA-01',
    telemetry: {
      rpm: 2420,
      cht: 174.2,
      egt: 692.0,
      oilPressure: 68.4,
      oilTemperature: 82.1,
      fuelFlow: 32.1,
      vibration: 1.85,
      vibrationRmsG: 1.24,
      batteryVoltage: 28.2,
      alternatorCurrent: 34.5,
      manifoldPressure: 28.9,
      cylinderTemps: [174.2, 172.5, 176.0, 173.8],
      harmonicFreq: 124.8,
      twinDivergenceMae: 0.8,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 99.4,
      syncStatus: 'SYNCHRONIZED',
      syntheticTwinId: 'SYNTHETIC TWIN D-01',
      azimuth: 114,
      elevation: -12.4,
      frameRefreshHz: 60,
      latencyMs: 12,
      thermodynamicParametersCount: 112,
      divergenceScoreMae: 0.8,
      subsystems: {
        fuelDelivery: 98,
        coolingAirflow: 96,
        lubricationSump: 97,
        dualMagnetosSpark: 99,
      },
      cylinderHotspots: [
        { id: 1, label: 'CYL-1', temp: 174, status: 'NOMINAL', xPercent: 36, yPercent: 32 },
        { id: 2, label: 'CYL-2', temp: 172, status: 'NOMINAL', xPercent: 64, yPercent: 34 },
        { id: 3, label: 'CYL-3', temp: 176, status: 'NOMINAL', xPercent: 34, yPercent: 60 },
        { id: 4, label: 'CYL-4', temp: 173, status: 'NOMINAL', xPercent: 66, yPercent: 62 },
      ],
    },
  },
  {
    id: 'eng-02',
    index: 1,
    name: 'Lycoming O-320 (Port Outboard)',
    model: 'Lycoming O-320 Aero Piston',
    position: 'Port Outboard',
    health: 84,
    status: 'WATCH // ELEVATED CHT',
    statusColor: '#f59e0b',
    rul: 162,
    callsign: 'PORT OUTBOARD // MOD-02',
    engineNumber: 'ENG-02-PO',
    serialNumber: 'SN-LYC-90143',
    totalFlightHours: 412.1,
    uavId: 'UAV-DHRUVA-01',
    telemetry: {
      rpm: 2380,
      cht: 208.6,
      egt: 718.0,
      oilPressure: 64.2,
      oilTemperature: 89.4,
      fuelFlow: 34.2,
      vibration: 2.85,
      vibrationRmsG: 1.82,
      batteryVoltage: 28.0,
      alternatorCurrent: 35.1,
      manifoldPressure: 28.5,
      cylinderTemps: [194.2, 218.4, 201.0, 196.8],
      harmonicFreq: 122.4,
      twinDivergenceMae: 2.4,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 96.8,
      syncStatus: 'DRIFT_DETECTED',
      syntheticTwinId: 'SYNTHETIC TWIN D-02',
      azimuth: 118,
      elevation: -11.8,
      frameRefreshHz: 60,
      latencyMs: 14,
      thermodynamicParametersCount: 112,
      divergenceScoreMae: 2.4,
      subsystems: {
        fuelDelivery: 91,
        coolingAirflow: 78,
        lubricationSump: 86,
        dualMagnetosSpark: 94,
      },
      cylinderHotspots: [
        { id: 1, label: 'CYL-1', temp: 194, status: 'NOMINAL', xPercent: 36, yPercent: 32 },
        { id: 2, label: 'CYL-2', temp: 218, status: 'WARNING', xPercent: 64, yPercent: 34 },
        { id: 3, label: 'CYL-3', temp: 201, status: 'NOMINAL', xPercent: 34, yPercent: 60 },
        { id: 4, label: 'CYL-4', temp: 196, status: 'NOMINAL', xPercent: 66, yPercent: 62 },
      ],
    },
  },
  {
    id: 'eng-03',
    index: 2,
    name: 'Lycoming O-320 (Starboard Inboard)',
    model: 'Lycoming O-320 Aero Piston',
    position: 'Starboard Inboard',
    health: 71,
    status: 'WARNING // HIGH HARMONIC VIB',
    statusColor: '#ef4444',
    rul: 88,
    callsign: 'STARBOARD INBOARD // MOD-03',
    engineNumber: 'ENG-03-SI',
    serialNumber: 'SN-LYC-90144',
    totalFlightHours: 524.8,
    uavId: 'UAV-DHRUVA-01',
    telemetry: {
      rpm: 2450,
      cht: 188.0,
      egt: 704.0,
      oilPressure: 56.4,
      oilTemperature: 94.2,
      fuelFlow: 35.8,
      vibration: 4.85,
      vibrationRmsG: 3.14,
      batteryVoltage: 27.9,
      alternatorCurrent: 36.2,
      manifoldPressure: 28.2,
      cylinderTemps: [186.0, 189.5, 187.2, 191.0],
      harmonicFreq: 138.6,
      twinDivergenceMae: 3.8,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 93.1,
      syncStatus: 'RESYNCING',
      syntheticTwinId: 'SYNTHETIC TWIN D-03',
      azimuth: 110,
      elevation: -13.1,
      frameRefreshHz: 60,
      latencyMs: 18,
      thermodynamicParametersCount: 112,
      divergenceScoreMae: 3.8,
      subsystems: {
        fuelDelivery: 88,
        coolingAirflow: 89,
        lubricationSump: 68,
        dualMagnetosSpark: 92,
      },
      cylinderHotspots: [
        { id: 1, label: 'CYL-1', temp: 186, status: 'NOMINAL', xPercent: 36, yPercent: 32 },
        { id: 2, label: 'CYL-2', temp: 189, status: 'NOMINAL', xPercent: 64, yPercent: 34 },
        { id: 3, label: 'CYL-3', temp: 187, status: 'NOMINAL', xPercent: 34, yPercent: 60 },
        { id: 4, label: 'CYL-4', temp: 191, status: 'CRITICAL', xPercent: 66, yPercent: 62 },
      ],
    },
  },
  {
    id: 'eng-04',
    index: 3,
    name: 'Lycoming O-320 (Starboard Outboard)',
    model: 'Lycoming O-320 Aero Piston',
    position: 'Starboard Outboard',
    health: 94,
    status: 'HEALTHY // OPTIMAL',
    statusColor: '#10b981',
    rul: 216,
    callsign: 'STARBOARD OUTBOARD // MOD-04',
    engineNumber: 'ENG-04-SO',
    serialNumber: 'SN-LYC-90145',
    totalFlightHours: 368.0,
    uavId: 'UAV-DHRUVA-01',
    telemetry: {
      rpm: 2410,
      cht: 176.5,
      egt: 688.0,
      oilPressure: 67.8,
      oilTemperature: 81.5,
      fuelFlow: 31.9,
      vibration: 1.92,
      vibrationRmsG: 1.30,
      batteryVoltage: 28.3,
      alternatorCurrent: 34.0,
      manifoldPressure: 29.0,
      cylinderTemps: [176.5, 174.0, 177.2, 175.1],
      harmonicFreq: 125.0,
      twinDivergenceMae: 0.9,
      timestamp: Date.now(),
    },
    twinState: {
      confidence: 99.1,
      syncStatus: 'SYNCHRONIZED',
      syntheticTwinId: 'SYNTHETIC TWIN D-04',
      azimuth: 112,
      elevation: -12.0,
      frameRefreshHz: 60,
      latencyMs: 11,
      thermodynamicParametersCount: 112,
      divergenceScoreMae: 0.9,
      subsystems: {
        fuelDelivery: 97,
        coolingAirflow: 98,
        lubricationSump: 96,
        dualMagnetosSpark: 98,
      },
      cylinderHotspots: [
        { id: 1, label: 'CYL-1', temp: 176, status: 'NOMINAL', xPercent: 36, yPercent: 32 },
        { id: 2, label: 'CYL-2', temp: 174, status: 'NOMINAL', xPercent: 64, yPercent: 34 },
        { id: 3, label: 'CYL-3', temp: 177, status: 'NOMINAL', xPercent: 34, yPercent: 60 },
        { id: 4, label: 'CYL-4', temp: 175, status: 'NOMINAL', xPercent: 66, yPercent: 62 },
      ],
    },
  },
];

export const INITIAL_ALERTS: FaultEvent[] = [
  {
    id: 'flt-101',
    engineId: 'eng-02',
    engineIndex: 1,
    severity: 'WARNING',
    title: 'Cylinder #2 Head Temperature Excursion',
    component: 'Cylinder #2 Cooling Baffle',
    description: 'CHT reached 218.4°C (+18°C above loiter baseline). Thermodynamic twin indicates airflow stagnation.',
    timestamp: '14:22:10Z',
    actionLabel: 'Inspect Baffle Flow',
    acknowledged: false,
    subsystem: 'Cooling Airflow Matrix',
    value: '218.4°C',
    threshold: '200.0°C',
  },
  {
    id: 'flt-102',
    engineId: 'eng-03',
    engineIndex: 2,
    severity: 'CRITICAL',
    title: 'Starboard Journal Bearing Harmonic Vibration Spike',
    component: 'Crankshaft Main Bearing #3',
    description: 'Broadband vibration RMS exceeded 4.8 mm/s at 138.6 Hz. Stage 2 spalling probability estimated at 88.4%.',
    timestamp: '14:19:45Z',
    actionLabel: 'Limit RPM to 2200',
    acknowledged: false,
    subsystem: 'Propulsion Train Mechanics',
    value: '4.85 mm/s',
    threshold: '3.50 mm/s',
  },
  {
    id: 'flt-103',
    engineId: 'eng-02',
    engineIndex: 1,
    severity: 'WATCH',
    title: 'Oil Sump Return Line Temperature Creep',
    component: 'Oil Cooler Scavenge',
    description: 'Oil temperature climbing at 0.4°C/min; viscosity index degraded by 4.2%.',
    timestamp: '14:15:30Z',
    actionLabel: 'Monitor Oil Delta',
    acknowledged: true,
    subsystem: 'Lubrication Sump',
    value: '89.4°C',
    threshold: '90.0°C',
  },
];

export const INITIAL_MRO_TASKS: MaintenanceRecord[] = [
  {
    id: 'mro-01',
    engineId: 'eng-03',
    engineIndex: 2,
    title: 'Mandatory Borescope & Harmonic Bearing Overhaul',
    component: 'Crankshaft Journal #3',
    severity: 'CRITICAL',
    hoursRemaining: 18,
    description: 'Vibration pattern matches bearing race micro-pitting. Ground abort mandatory upon landing.',
    statusText: 'GROUND ABORT MANDATORY',
    priority: 'HIGH',
    recommendedAction: 'Replace crankshaft bearing assembly PK-320-B and flush scavenge pump.',
    lastServiceDate: '2026-08-12',
  },
  {
    id: 'mro-02',
    engineId: 'eng-02',
    engineIndex: 1,
    title: 'Cylinder #2 Cooling Baffle Shroud Realignment',
    component: 'Nacelle Cooling Shroud',
    severity: 'WARNING',
    hoursRemaining: 46,
    description: 'Inspect convective air vane seal and clear boundary layer intake obstruction.',
    statusText: 'PRIORITY AT POST-FLIGHT',
    priority: 'HIGH',
    recommendedAction: 'Inspect rubber seal inter-cylinder baffles and realign intake ducting.',
    lastServiceDate: '2026-08-20',
  },
  {
    id: 'mro-03',
    engineId: 'eng-01',
    engineIndex: 0,
    title: 'Magneto Dual-Spark Timing Calibration',
    component: 'Bendix Dual Magneto',
    severity: 'NORMAL',
    hoursRemaining: 124,
    description: 'Routine 100-hr magneto point inspection and internal capacitor resistance check.',
    statusText: 'ROUTINE SCHEDULED',
    priority: 'LOW',
    recommendedAction: 'Measure magneto E-gap and verify 25° BTDC timing alignment.',
    lastServiceDate: '2026-08-28',
  },
];

export const INITIAL_CANDIDATE_CONFIGS: CandidateConfig[] = [
  {
    id: 'alpha',
    name: 'Candidate Alpha (AI Recommended)',
    subtitle: 'Balanced High-Altitude Loiter Profile',
    tag: 'RECOMMENDED',
    isAiRecommended: true,
    fuelBurnLh: 28.6,
    fuelDeltaText: '-8.4% burn rate',
    thermalCht: 176.4,
    thermalDeltaText: '-12°C margin',
    wearRate: 'LOW // 0.04 um/hr',
    estRulHours: 232,
    rulDeltaText: '+48 hrs life extension',
    missionLoiterHours: 8.4,
    loiterDeltaText: '+1.2 hrs endurance',
    envelopeStatus: 'PASS // MIL-STD VALIDATED',
    envelopeValid: true,
    lambda: 1.05,
    timing: 22.5,
    rpm: 2350,
    cowlCht: 178,
  },
  {
    id: 'beta',
    name: 'Candidate Beta (Rapid Response Ingress)',
    subtitle: 'High-Thrust Sprint Profile',
    tag: 'SPRINT',
    fuelBurnLh: 36.2,
    fuelDeltaText: '+14.2% burn rate',
    thermalCht: 212.0,
    thermalDeltaText: '+24°C thermal stress',
    wearRate: 'ELEVATED // 0.12 um/hr',
    estRulHours: 142,
    rulDeltaText: '-42 hrs life reduction',
    missionLoiterHours: 5.6,
    loiterDeltaText: '-1.6 hrs loiter',
    envelopeStatus: 'WARNING // NEAR THERMAL CEILING',
    envelopeValid: true,
    lambda: 0.92,
    timing: 26.0,
    rpm: 2650,
    cowlCht: 185,
  },
  {
    id: 'gamma',
    name: 'Candidate Gamma (Ultra-Lean Cruise)',
    subtitle: 'Maximum Endurance Eco Profile',
    tag: 'REJECTED BY TWIN',
    isRejected: true,
    fuelBurnLh: 25.1,
    fuelDeltaText: '-18.5% burn rate',
    thermalCht: 228.4,
    thermalDeltaText: '+42°C EXCURSION DANGER',
    wearRate: 'CRITICAL // KNOCK DETECTED',
    estRulHours: 76,
    rulDeltaText: '-108 hrs accelerated fatigue',
    missionLoiterHours: 9.1,
    loiterDeltaText: 'UNSAFE // REJECTED',
    envelopeStatus: 'FAIL // CHT EXCEEDS 220°C BOUND',
    envelopeValid: false,
    lambda: 1.14,
    timing: 24.0,
    rpm: 2200,
    cowlCht: 170,
    safetyViolationText: 'Severe detonation hazard on cylinder #2 and #3. FADEC veto applied.',
  },
];

export const INITIAL_TELEMETRY_HISTORY: TelemetryHistoryPoint[] = Array.from({ length: 24 }).map((_, i) => {
  const minAgo = (24 - i) * 2;
  return {
    timeLabel: `-${minAgo}m`,
    timeSec: i * 120,
    rpm: 2400 + Math.round(Math.sin(i * 0.4) * 45),
    cht: +(172 + Math.sin(i * 0.3) * 6 + (i > 16 ? 12 : 0)).toFixed(1),
    egt: +(690 + Math.cos(i * 0.35) * 18).toFixed(1),
    oil: +(66 + Math.sin(i * 0.25) * 4).toFixed(1),
    fuel: +(32.4 + Math.cos(i * 0.2) * 1.8).toFixed(1),
    vibration: +(1.9 + Math.sin(i * 0.5) * 0.4 + (i > 18 ? 1.4 : 0)).toFixed(2),
    battery: 28.2,
    alternator: 34.8,
  };
});
