import { EngineInstance, Mission, CandidateConfig, FaultEvent, Telemetry, TelemetryPoint } from '../types/tuningTypes';

export const INITIAL_ENGINES: EngineInstance[] = [
  {
    id: 'eng01',
    name: 'PROPULSION UNIT 01 // LYCOMING O-320 MOD',
    model: 'Lycoming O-320-D2J Turbo-Normalized',
    serialNumber: 'L-29481-27A',
    type: 'Horizontal Opposed 4-Cylinder Aero Piston',
    totalFlightHours: 342.6,
    baseRulHours: 184,
    currentHealth: 94.2,
    healthStatus: 'OPTIMIZED',
    nominalRpmRange: [2200, 2700],
    nominalChtMax: 190,
    status: 'ONLINE',
  },
  {
    id: 'eng02',
    name: 'PROPULSION UNIT 02 // ROTAX 914-F HYBRID',
    model: 'Rotax 914-F3 Turbocharged 115HP',
    serialNumber: 'RX-914-8842',
    type: '4-Cylinder 4-Stroke Boxer Dual Ignition',
    totalFlightHours: 188.4,
    baseRulHours: 260,
    currentHealth: 98.1,
    healthStatus: 'NOMINAL',
    nominalRpmRange: [2100, 2800],
    nominalChtMax: 185,
    status: 'ONLINE',
  },
  {
    id: 'eng03',
    name: 'PROPULSION UNIT 03 // CONTINENTAL CD-170',
    model: 'Continental CD-170 FADEC Jet-A Piston',
    serialNumber: 'CD-170-0492',
    type: 'Turbo Diesel In-Line 4 Common-Rail',
    totalFlightHours: 512.0,
    baseRulHours: 110,
    currentHealth: 88.5,
    healthStatus: 'DEGRADED',
    nominalRpmRange: [2000, 2600],
    nominalChtMax: 195,
    status: 'WARNING',
  },
  {
    id: 'eng04',
    name: 'PROPULSION UNIT 04 // BENCH TEST RIG #4',
    model: 'Experimental Dyno Test Rig 160HP',
    serialNumber: 'BENCH-RIG-04',
    type: 'Instrumented Static Testbench Array',
    totalFlightHours: 78.2,
    baseRulHours: 320,
    currentHealth: 99.5,
    healthStatus: 'NOMINAL',
    nominalRpmRange: [1800, 2900],
    nominalChtMax: 200,
    status: 'CALIBRATING',
  },
];

export const INITIAL_MISSIONS: Mission[] = [
  {
    id: 'isr',
    name: 'HIGH ALTITUDE ISR (25,000 FT // -34°C COLD TEMP)',
    type: 'Intelligence, Surveillance & Reconnaissance',
    phase: 'HIGH CRUISE LOITER',
    targetAltitudeFt: 25000,
    ambientTempC: -34,
    baroInHg: 29.92,
    densityAltitudeFt: 26480,
    intakeAirO2Kpa: 11.4,
    progressPercent: 48,
    elapsedHours: 4.8,
    totalPlannedHours: 10.0,
    fuelCapacityLiters: 280,
    currentFuelLiters: 174,
    burnRateLh: 27.2,
    uavCallsign: 'DHRUV-ALPHA-07',
    linkStatus: 'MALE-LINK-01 // ENCRYPTED',
  },
  {
    id: 'sprint',
    name: 'LOW ALTITUDE TACTICAL SPRINT (1,500 FT // +38°C)',
    type: 'Low-Level Penetration / Tactical Dash',
    phase: 'TACTICAL INGRESS',
    targetAltitudeFt: 1500,
    ambientTempC: 38,
    baroInHg: 30.04,
    densityAltitudeFt: 3200,
    intakeAirO2Kpa: 19.8,
    progressPercent: 22,
    elapsedHours: 1.1,
    totalPlannedHours: 5.0,
    fuelCapacityLiters: 280,
    currentFuelLiters: 232,
    burnRateLh: 36.4,
    uavCallsign: 'DHRUV-RAPID-03',
    linkStatus: 'LOS-UHF-02 // DUAL SECURE',
  },
  {
    id: 'endurance',
    name: 'MAXIMUM LOITER ENDURANCE (12,000 FT // +05°C)',
    type: 'Extended Station Loiter & Persistent Watch',
    phase: 'HIGH CRUISE LOITER',
    targetAltitudeFt: 12000,
    ambientTempC: 5,
    baroInHg: 29.90,
    densityAltitudeFt: 12850,
    intakeAirO2Kpa: 15.6,
    progressPercent: 65,
    elapsedHours: 7.8,
    totalPlannedHours: 14.0,
    fuelCapacityLiters: 320,
    currentFuelLiters: 138,
    burnRateLh: 23.5,
    uavCallsign: 'DHRUV-LOITER-09',
    linkStatus: 'SATCOM-GEO-04 // PRIMARY',
  },
];

export const CANDIDATE_CONFIGS: CandidateConfig[] = [
  {
    id: 'alpha',
    name: 'Factory Baseline',
    subtitle: 'STANDARD OEM TACTICAL MAPPING',
    tag: 'CONFIG ALPHA',
    fuelBurnLh: 32.5,
    thermalCht: 178,
    wearRate: 'Nominal Baseline',
    estRulHours: 184,
    missionLoiterHours: 10.5,
    envelopeStatus: 'PASS (100%)',
    envelopeValid: true,
    lambda: 1.00,
    timing: 24.0,
    rpm: 2400,
    cowlCht: 175,
  },
  {
    id: 'beta',
    name: 'High-Alt Lean Cruise',
    subtitle: 'OPTIMIZED THERMODYNAMIC SWEEP',
    tag: 'CONFIG BETA',
    isAiRecommended: true,
    fuelBurnLh: 27.2,
    fuelDeltaText: '+16.3% ECON',
    thermalCht: 182,
    thermalDeltaText: '+4°C STABLE',
    wearRate: '+0.02%/hr WEAR',
    estRulHours: 178,
    rulDeltaText: '-3.2% DELTA',
    missionLoiterHours: 12.8,
    loiterDeltaText: '+2.3 HRS TACTICAL',
    envelopeStatus: 'PASS // 100% VALID',
    envelopeValid: true,
    lambda: 0.98,
    timing: 24.0,
    rpm: 2450,
    cowlCht: 176,
  },
  {
    id: 'gamma',
    name: 'Lean Overdrive',
    subtitle: 'REJECTED // UNSAFE LIMITS',
    tag: 'CONFIG GAMMA',
    isRejected: true,
    fuelBurnLh: 24.1,
    thermalCht: 218,
    wearRate: 'Severe Degr.',
    estRulHours: 62,
    rulDeltaText: '-66% CRITICAL',
    missionLoiterHours: 0,
    loiterDeltaText: 'N/A (ABORT)',
    envelopeStatus: 'FAIL: CYL 2 & 3 +18°C',
    envelopeValid: false,
    lambda: 1.14,
    timing: 27.5,
    rpm: 2750,
    cowlCht: 190,
    safetyViolationText: 'Candidate Gamma exceeds thermal CHT safe criteria by +18°C on Cylinders 2 & 3.',
  },
];

export const INITIAL_ALERTS: FaultEvent[] = [
  {
    id: 'FLT-1082',
    timestamp: '14:26:41 UTC',
    severity: 'WARNING',
    subsystem: 'THERMAL / CYL-2',
    description: 'Cylinder #2 head temperature transient peak observed (+6°C above fleet mean).',
    value: '183.4°C',
    threshold: '185.0°C',
    acknowledged: false,
  },
  {
    id: 'FLT-1079',
    timestamp: '14:22:15 UTC',
    severity: 'WATCH',
    subsystem: 'OIL SCAVENGE',
    description: 'High-altitude oil kinematic viscosity marginal threshold at FL250 transition.',
    value: '68.2 cSt',
    threshold: '75.0 cSt',
    acknowledged: false,
  },
  {
    id: 'FLT-1064',
    timestamp: '14:15:02 UTC',
    severity: 'NORMAL',
    subsystem: 'IGNITION / MAGNETO A',
    description: 'Primary electronic ignition advance curvature calibrated successfully to 24.0° BTDC.',
    value: '24.0° BTDC',
    threshold: 'NOMINAL',
    acknowledged: true,
  },
  {
    id: 'FLT-1045',
    timestamp: '13:58:30 UTC',
    severity: 'CRITICAL',
    subsystem: 'TURBO-WASTEGATE',
    description: 'Prior testbench excursion logged on historical sweep (Resolved in current active matrix).',
    value: '84.8 bar',
    threshold: '85.0 bar',
    acknowledged: true,
  },
];

export const INITIAL_TELEMETRY: Telemetry = {
  rpm: 2450,
  cht: 182,
  egt: 810,
  oilPressure: 64.2,
  oilTemp: 84.5,
  fuelFlow: 27.2,
  vibration: 0.18,
  batteryVoltage: 28.4,
  alternatorCurrent: 34.6,
  cylinderCht: [179, 182, 181, 180],
  cylinderPressure: [71.8, 72.4, 71.9, 72.1],
  knockIndex: 0.00,
  lastUpdated: Date.now(),
};

// Generate 1800 initial points for telemetry charts (1 hour at 2s interval)
export function generateInitialTelemetryHistory(count = 1800): TelemetryPoint[] {
  const points: TelemetryPoint[] = [];
  const now = Date.now();
  const stepMs = 2000; // 2 sec intervals

  for (let i = count - 1; i >= 0; i--) {
    const time = now - i * stepMs;
    const date = new Date(time);
    const timeLabel = `${String(date.getUTCHours()).padStart(2, '0')}:${String(date.getUTCMinutes()).padStart(2, '0')}:${String(date.getUTCSeconds()).padStart(2, '0')}`;
    
    // Natural subtle noise
    const noise = Math.sin(i * 0.4) * 1.5;
    const noise2 = Math.cos(i * 0.3) * 0.8;

    points.push({
      timestamp: time,
      timeLabel,
      rpm: Math.round(2450 + noise * 12),
      cht: parseFloat((181.5 + noise2 * 1.2).toFixed(1)),
      egt: Math.round(808 + noise * 4),
      oilPressure: parseFloat((64.0 + noise2 * 0.4).toFixed(1)),
      oilTemp: parseFloat((84.2 + noise * 0.3).toFixed(1)),
      fuelFlow: parseFloat((27.2 + noise2 * 0.3).toFixed(1)),
      vibration: parseFloat((0.18 + Math.abs(noise * 0.015)).toFixed(2)),
      batteryVoltage: parseFloat((28.4 + noise2 * 0.05).toFixed(1)),
      alternatorCurrent: parseFloat((34.6 + noise * 0.4).toFixed(1)),
      health: parseFloat((94.5 - (count - 1 - i) * 0.015 + noise2 * 0.1).toFixed(1)),
    });
  }

  return points;
}
